### ISSUE TITLE
Make cs2.md easier to find

### ISSUE THREAD

**Issue by orblivion** [go-ap/fedbox#8]
I was previously considering posting an issue saying that fedbox could benefit a lot from a little bit of documentation, so that a beginner such as myself would have an idea of what I'm looking at, and know where to begin looking. But then I found https://github.com/go-ap/fedbox/blob/master/doc/c2s.md and that at least covers much of what I was looking for. My humble suggestion would be to make this file easier to find. Perhaps you could link to it from the repo's root README as you do for INSTALL.md, but make it more clear that it gives a good overview of what's in this package. Alternately you could just put it in the README.

**Comment by mariusor** [comment]
Thank you @orblivion for the suggestion, and apologies for taking this long to get to this, I'm not watching the issues on GitHub too much, in favour of the mailing list. Based on your feedback on HN I also added a link to the wiki.

Please check the [README](https://github.com/go-ap/fedbox#further-reading) and let me know if it's more visible now. :)
